apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip
  template:
    metadata:
      labels:
        name: kube-vip
    spec:
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v0.6.0
          imagePullPolicy: IfNotPresent
          args:
            - manager
          env:
            - name: vip_interface
              value: "enp5s0"
            - name: vip_arp
              value: "true"
            - name: vip_address
              value: "192.168.68.20"
            - name: lb_enable
              value: "true"
            - name: lb_port
              value: "6443"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW