deployment:
  kind: DaemonSet

additionalArguments:
  - "--log.level=DEBUG"
  - "--api.dashboard=true"

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: "10.0.10.2"

ports:
  web:
    port: 80
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    exposedPort: 443
    protocol: TCP

ingressRoute:
  dashboard:
    enabled: true